name: update formula

on:
  push:
    branches:
      - main
    paths:
      - 'Versions/**'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: "cloud-gov/homebrew-cloudgov"
	token: ${{secrets.CGCIBOT_PAT}}
    - name: Generate Formula
      working-directory: ./Versions
      run: |
        pwd
        ./gen_formula.sh
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: cg-ci-bot

