name: update formula

on:
  push:
    branches:
      - main
    paths:
      - 'Versions/**'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{secrets.CGCIBOT_PAT}}
    - name: Import bot's GPG key for signing commits
      id: import-gpg
      uses: crazy-max/ghaction-import-gpg@v4
      with:
        gpg_private_key: ${{ secrets.CGCIBOT_GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.CGCIBOT_GPG_PASSPHRASE }}
        git_config_global: true
        git_user_signingkey: true
        git_commit_gpgsign: true
    - name: Generate Formula
      working-directory: ./Versions
      run: |
        pwd
        ./gen_formula.sh
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: cg-ci-bot

